image: gcc

variables:
  DOCKER_DRIVER: overlay2

cache:
    key: one-key-to-rull-them-all
    paths:
        - gsoap-2.8/
        - generated/

before_script:
    - apt update && apt -y install flex bison byacc make m4 openssl libssl-dev zlib1g-dev libcrypto++6 libconfig-dev libmosquitto-dev
    - git submodule update --init --recursive

build:
    stage: build    
    script:
        - ./build-deb
    artifacts:
        paths:
            - start_scripts/
            - onvif_srvd
            - onvif_srvd_debug
            - onvif-srvd-*.deb
    rules:
        - when: manual  
