image: gcc

before_script:
    - apt update && apt -y install flex bison byacc make m4 openssl libssl-dev zlib1g-dev libcrypto++6 libconfig-dev libmosquitto-dev

build:
    stage: build    
    script:
        - make WSSE_ON=1
    artifacts:
        paths:
            - start_scripts
            - onvif_svrd
            - onvif_svrd_debug
