image: debian:bullseye-slim

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
 
#cache:
#    key: one-key-to-rull-them-all
#    paths:
#        - gsoap-2.8/
#        - generated/

before_script:
    - apt update && apt -y install git git-lfs cmake build-essential ssh-client flex bison byacc m4 libconfig++9v5 libconfig++-dev mosquitto libmosquitto-dev mosquitto-clients mosquitto-dev libgstreamer1.0-dev gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-vaapi libgstreamer-plugins-base1.0-dev libgstrtspserver-1.0-0 libgstrtspserver-1.0-dev openssl libssl-dev zlib1g-dev libcrypto++8 unzip

build:
    stage: build    
    script:
        - ./build-deb.sh
    artifacts:
        paths:
            - start_scripts/
            - onvif_srvd
            - onvif_srvd_debug
            - onvif-srvd-*.deb
    rules:
        - when: manual  
