image: gcc

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
 
#cache:
#    key: one-key-to-rull-them-all
#    paths:
#        - gsoap-2.8/
#        - generated/

before_script:
    - apt update && apt -y install ssh-client flex bison byacc make m4 openssl libssl-dev zlib1g-dev libcrypto++8 libconfig-dev libmosquitto-dev

build:
    stage: build    
    script:
        - ./build-deb.sh
    artifacts:
        paths:
            - start_scripts/
            - onvif_srvd
            - onvif_srvd_debug
            - onvif-srvd-*.deb
    rules:
        - when: manual  
