FIND_PATH(MOSQUITTO_INCLUDE_DIR mosquitto /usr/include /usr/local/include)

FIND_LIBRARY(MOSQUITTO_LIBRARY NAMES mosquitto PATH /usr/lib /usr/local/lib)

IF (MOSQUITTO_INCLUDE_DIR AND MOSQUITTO_LIBRARY)
    SET(MOSQUITTO_FOUND TRUE)
ENDIF ( MOSQUITTO_INCLUDE_DIR AND MOSQUITTO_LIBRARY)

IF (MOSQUITTO_FOUND)
    IF (NOT MOSQUITTO_FIND_QUIETLY)
        MESSAGE(STATUS "Found MOSQUITTO: ${MOSQUITTO_LIBRARY}")
    ENDIF (NOT  MOSQUITTO_FIND_QUIETLY)
ELSE(MOSQUITTO_FOUND)
    IF (Mosquitto_FIND_REQUIRED)
        IF(NOT MOSQUITTO_INCLUDE_DIR)
            MESSAGE(FATAL_ERROR "Could not find Mosquitto header file!")
        ENDIF(NOT MOSQUITTO_INCLUDE_DIR)

        IF(NOT MOSQUITTO_LIBRARY)
            MESSAGE(FATAL_ERROR "Could not find Mosquitto library file!")
        ENDIF(NOT MOSQUITTO_LIBRARY)
    ENDIF (Mosquitto_FIND_REQUIRED)
ENDIF (MOSQUITTO_FOUND)
